# Generated by Django 4.2.1 on 2023-05-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nationality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='residence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='styles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='yearofbirth',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='yearofdeath',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='year',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
